# Generated by Django 6.0.2 on 2026-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='csvs/')),
                ('total_records', models.IntegerField(default=0)),
                ('avg_pressure', models.FloatField(default=0.0)),
                ('avg_temp', models.FloatField(default=0.0)),
                ('type_distribution', models.JSONField(default=dict)),
            ],
        ),
    ]
